TESTUTILITY:testUtility.o utility.o
	gcc -o TESTUTILITY testUtility.o utility.o
utility.o:../utility.c
	gcc -o utility.o -c ../utility.c
testUtility.o:testUtility.c
	gcc -o testUtility.o -c testUtility.c
