TESTMANAGER:testManager.o manager.o student.o book.o utility.o
	gcc -o TESTMANAGER testManager.o manager.o student.o book.o utility.o
manager.o:../manager.c
	gcc -c ../manager.c -o manager.o
testManager.o:testManager.c
	gcc -c testManager.c -o testManager.o
student.o:../student.c
	gcc -c ../student.c -o student.o
book.o:../book.c
	gcc -c ../book.c -o book.o
utility.o:../utility.c
	gcc -c ../utility.c -o utility.o
